version: "3.9"

networks:
  news-tracker-net:

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - news-tracker-net

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
    networks:
      - news-tracker-net

  mongodb:
    image: bitnami/mongodb:latest
    environment:
      MONGODB_ROOT_PASSWORD: password123
      MONGODB_USERNAME: mongo-user
      MONGODB_PASSWORD: password123
      MONGODB_DATABASE: news-tracker
    ports:
      - 27017:27017
    networks:
      - news-tracker-net

  news-tracker-core:
    image: news-tracker-core:latest
    ports:
      - "8080:8080"
    networks:
      - news-tracker-net
    depends_on:
      - mongodb
      - kafka
    environment:
      HOST: 0.0.0.0
      PORT: 8080
      MONGO_HOST: mongodb
      MONGO_USER: mongo-user
      MONGO_PASSWORD: password123
      KAFKA_SERVERS: kafka:29092
      KAFKA_GROUP_ID: newstracker-group
      DEEPL_BASE_URI: https://api.deepl.com/v2
      DEEPL_AUTH_KEY: 

  news-tracker-clients-de:
    image: news-tracker-clients:latest
    networks:
      - news-tracker-net
    depends_on:
      - mongodb
      - kafka
    environment:
      MONGO_HOST: mongodb
      MONGO_USER: mongo-user
      MONGO_PASSWORD: password123
      KAFKA_SERVERS: kafka:29092
      KAFKA_GROUP_ID: newstracker-group
      YAHOO_NAME_SUFFIX: "de"
      YAHOO_API_KEY: 
      YAHOO_POLL_INTERVAL: 1m
      YAHOO_REGION: DE

  news-tracker-clients-en:
    image: news-tracker-clients:latest
    networks:
      - news-tracker-net
    depends_on:
      - mongodb
      - kafka
    environment:
      MONGO_HOST: mongodb
      MONGO_USER: mongo-user
      MONGO_PASSWORD: password123
      KAFKA_SERVERS: kafka:29092
      KAFKA_GROUP_ID: newstracker-group
      YAHOO_NAME_SUFFIX: "en"
      YAHOO_API_KEY: 
      YAHOO_POLL_INTERVAL: 1m
      YAHOO_REGION: EN

  news-tracker-frontend:
    image: news-tracker-frontend:latest
    depends_on:
      - news-tracker-core
    ports:
      - "80:3000"
    networks:
      - news-tracker-net
    environment:
      NEXT_PUBLIC_SERVER_ADDRESS: http://news-tracker-core:8080
      NEXT_PUBLIC_SERVER_WS_ADDRESS: ws://news-tracker-core:8080
