version: "3.9"

networks:
  news-tracker-net:

services:

  mongodb:
    image: bitnami/mongodb:latest
    environment:
      MONGODB_ROOT_PASSWORD: password123
      MONGODB_USERNAME: mongo-user
      MONGODB_PASSWORD: password123
      MONGODB_DATABASE: news-tracker
    ports:
      - 27017:27017
    networks:
      - news-tracker-net

  news-tracker-core:
    image: news-tracker-core:latest
    ports:
      - "8080:8080"
    networks:
      - news-tracker-net
    depends_on:
      - mongodb
    environment:
      MONGO_HOST: mongodb
      MONGO_USER: mongo-user
      MONGO_PASSWORD: password123

  news-tracker-frontend:
    image: news-tracker-frontend:latest
    depends_on:
      - news-tracker-core
    ports:
      - "80:3000"
    networks:
      - news-tracker-net
    environment:
      SERVER_ADDRESS: http://news-tracker-core:8080
