### This file requires the REST Client VS Code extension
### https://marketplace.visualstudio.com/items?itemName=humao.rest-client

@endpoint = http://localhost:8080/api

### Show all
GET {{endpoint}}/articles


### Show by id
GET {{endpoint}}/articles/6455d7cd41b8b40c25b9a713

### Create
POST {{endpoint}}/articles
Content-Type: application/json

{"title": "title #1","content": "Simple article","createdAt": "2023-05-19T14:30:45.123Z","addedAt": "2023-05-19T14:30:45.123Z","language": "de","authors": "author #1"}

### Health status
GET http://localhost:8080/health/status

### get translation
GET {{endpoint}}/translations/645f06c3becd3d1b4306d7b2

### create translation
POST {{endpoint}}/translations/645f06c3becd3d1b4306d7b2/localizations/uk


### DeepL
GET https://api-free.deepl.com/v2/usage
Authorization: DeepL-Auth-Key 


### DeepL translate
POST https://api-free.deepl.com/v2/translate
Authorization: DeepL-Auth-Key 
Content-Type: application/json

{
  "text": ["Hello World!", "The sun is shining."],
  "source_lang": "EN",
  "target_lang": "ru",
  "tag_handling": "html"
}
